name: Deliver container

on: push

jobs:
  delivery:
    runs-on: ubuntu-latest
    name: Deliver container
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: create .env file
        env:
          MYSQL_DATABASE: ${{ secrets.DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          mkdir envsql
          touch envsql/.envsql
          echo MYSQL_DATABASE="$MYSQL_DATABASE" >> .envsql/.envsql
          echo MYSQL_ROOT_PASSWORD="$MYSQL_ROOT_PASSWORD" >> .envsql/.envsql
          ls -a
          cat envsql/.envsql
        shell: bash

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/basicproject_db:latest ./database

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/basicproject_db:latest